
email: nezuko2038@gmail.com

site.lang: ja
site.author: nezuko2038 
baseurl: "/journal" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com



# Build settings
markdown: kramdown


plugins:
    - jekyll-titles-from-headings




