= ファッションに関心のない私が印象診断へ行ってきた話
:page-layout: post
:page-category: 美容健康
:page-tags: [印象診断 ]
:page-description:
:revdate:  2018-02-03 00:00:00 +0900
:toc:

== 印象診断へ行ったきっかけ

おしゃれや美容に関心のない私が何故印象診断を受けたかというと、
ちょっとは良い身なりをしないと思いつつ、アドバイスをしてくれるような友がいないため、プロに判断を仰ごうということになりました。


== 印象診断とは

「初対面の人から、自分がどう見られているか」を教えてくれる診断です。
大丸松坂屋で受けることができます。

私の場合は静岡で受けました。
https://dmdepart.jp/fashionnavi/shizuoka/index.htm


> 顔の形や目・鼻などのパーツの特徴を拝見し、
> 専門家の情報データをもとにあなたの第一印象を分析。
> 診断結果に合わせて、おすすめコーディネートやアイテムをアドバイスいたします。

というもので、
診断タイプは以下の12タイプ。
キュート・ソフト・クラッシィ・ゴージャス・アクティブ・センシティブ・ミステリアス・フレッシュ・ボーイッシュ・トラディショナル・インテリジェント・クール


税込1,080円。時間は20分。

==  診断の流れ

診断は前半10分ぐらいで診断を受け、後半10分でアドバイスを受けることができます。


まず入口のところに受付のような机があり、そこで診断を受けます。
はじめに料金を支払い、住所名前等個人情報を記入します。
その後は軽く説明を受けたのち、
スタッフの方が私の顔の特徴を言いながらディスプレイに表示される選択肢を選んでいってくれます。

* 「面長ですね」
* 「どちかというと顔のパーツが中央に寄っていますね」
* 「一重ですね」
* 「一瞬赤くなったりしたのでブルーベースか悩ましいところですが、若干イエローベースですね」


回答を入力し終えると、最後に診断結果が表示されます。


私の診断結果は「クラッシィ」でした。
「高貴な」「優しい」一方で「親しみにくい」「気取った」印象なのだそうです。

スタッフの方のはじめの印象は「ソフト」「センシティブ」だったそうです。

後半は診断結果を元に、ファッションのポイントの説明を受けます。
基本はタイプ別の印象説明シートを元にプラスαのアドバイスをしてもらえます。

私の場合は

* 「服はシンプルに質感重視」
* 「遊び心に差し色も入れて」
* 「髪をおろしてみて、会議など発言したいときだけ耳を出すと変化をつけられる」

など。

「アジアンファッションは似合わない」とはっきり断言され、ああやっぱり、と思いました。
意外なものや突飛なアドバイスはなく、これまで自分の中で「これは似合う。似合わない」となんとなく考えていたものを、客観的に断言してもらえるといった感じでした。


最後帰り際の挨拶時に「クラッシィ」を「ストレートタイプ」と間違えて言われたので、
きっと骨格タイプはストレートなのでしょう。

==   まとめ

* 印象診断を受けることで、その人の第一印象がわかります。
* 私の第一印象は「クラッシィ」
* 印象診断で自分の印象を客観的に判断してもらえます。


