= 子鉄ソング
:page-layout: post
:page-category: 生活
:page-tags: [ music, 子鉄 ]
:page-description: 歩き出したと同時に鉄に目覚めた3歳児の息子のお気に入りの音楽をご紹介します。
:revdate:  2019-04-03  21:10 +0900
:toc:

== JR編

=== AMBITIOUS JAPAN!

video::15kgo5irnC0[youtube]
video::oaeepBZq4mk[youtube]


うた: TOKIO

散歩なんかでぐずっているときに「立ち止まらない、振り返らない！」と言うだけでシャキッとなりちゃんと歩いてくれます。

=== JR貨物社歌　春夏秋冬

video::l3awU_eeOiI[youtube]
video::GNKedDNldik[youtube]
うた：山本耕史

とにかくこれだけリピート再生しておけばいいぐらい、私も息子の大好きな曲です。


=== JR九州社歌 浪漫鉄道
video::jqtxdB8LiS4[youtube]

うた：ハイ・ファイ・セット
流れるような歌声はまるで、電車に乗って旅をしているようで、旅情あるれるメロディです。

=== JR西日本社歌　あしたへ向って

video::p6fUeYededc[youtube]

コーラスのためか、こどもには歌詞が聞きとりにくい模様。

=== JR東日本社歌 明け行く空に

video::3ai2SmT0uM8[youtube]

うた：サーカス



== その他

=== Dr.イエロー

video::jqtxdB8LiS4[youtube]

イェイイェイのかけ声がお気にいりです。

=== 【MOTOR MAN】新幹線ひかり

video::2JYcMPKyMnM[youtube]

うた：MOTOR MAN

「パンタグラフは6号車と12号車にあります」というところがお気にいりみたいです。

=== かもつれっしゃ

video::jVk8NG5Mw8w[youtube]
定番中の定番。
道で側溝の蓋の上を走るときによく歌っています。

=== かもつれっしゃのうた

video::PCN9stsMd-I[youtube]

作詞：香山美子
作曲：湯山昭
うた：山野さと子

=== モノレールのうた

video::pycJk0S3a7M[youtube]

作詞：伊藤アキラ
作曲：小林亜星
うた：山野さと子

得に説明もなく聞かせて、息子が次第にモノレールの歌だと理解している過程が楽しめました。
