= Subversion
:page-layout: post
:page-category: SCM
:page-tags: [svn ]
:page-description:  SVN関連コマンドの忘備録です。
:revdate:  2019-04-18  00:16 +0900
:toc:


== リポジトリ作成

svn_repository というSVNリポジトリを作成します。
[literal]
....
svnadmin create svn_repository
....



=== trunk,branches,tagsの作成

[literal]
....
svn co file:///`pwd`/svn_repository --no-auth-cache test
cd test
svn mkdir trunk branches tags
svn commit -m "Init"
....


== svn checkout

=== E210003: connection refused by the server
ERROR: Failed to check out svn://localhost/srv/jenkins_home/repos/svn_repository/trunk

=== svn: E180001: Unable to open repository
[literal]
....
svn: E170013: Unable to connect to a repository at URL 'file:///var/jenkins_home/repos/svn_repository'
svn: E180001: Unable to open repository 'file:///var/jenkins_home/repos/svn_repository'
svn: E160043: Expected FS format between '1' and '7'; found format '8'
....



== svn commit


[literal]
....
svn commit make.sh -m "add make.sh"
Adding         make.sh
Transmitting file data .done
Committing transaction...
Committed revision 2.
....

=== None of the environment variables SVN_EDITOR

`svn commit` 時に下記のようなエラーが表示されてコミットできない場合があります。

[literal]
....
svn: E205007: Commit failed (details follow):
svn: E205007: Could not use external editor to fetch log message; consider setting the $SVN_EDITOR environment variable or using the --message (-m) or --file (-F) options
svn: E205007: None of the environment variables SVN_EDITOR, VISUAL or EDITOR are set, and no 'editor-cmd' run-time configuration option was found
....

コミット時にコメントを記載するのに必要なエディタが指定されていないことによるエラーメッセージです。

コミット時に ｀-m` オプションでコメントを記述するか、エディタを指定するための環境変数 SVN_EDITOR、 VISUAL または　EDITOR　を指定する必要があります。


[source,sh]
.~/.bash_profile
----
VISUAL=vim; export VISUAL
----


=== svnserv

[literal]
....
svnserve  -d
....
